/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liangjie_app_Utils */

#ifndef _Included_liangjie_app_Utils
#define _Included_liangjie_app_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liangjie_app_Utils
 * Method:    compareintBitmap
 * Signature: ([III[III)D
 */
JNIEXPORT jdouble JNICALL Java_liangjie_app_Utils_compareintBitmap
  (JNIEnv *, jobject, jintArray, jint, jint, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
